// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/bucket/v1/createbucket": {
            "post": {
                "summary": "存储空间创建",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 31a165baebe6dec616b1f8f3207b4273",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "添加请求参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.BucketAddReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\",\"message\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/bucket/v1/del": {
            "delete": {
                "summary": "存储空间删除",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 31a165baebe6dec616b1f8f3207b4273",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "删除请求参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.DeleteBucketReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\",\"message\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/bucket/v1/detail": {
            "get": {
                "summary": "存储空间详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "存储空间ID",
                        "name": "bucket_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Bearer 31a165baebe6dec616b1f8f3207b4273",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\",\"message\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/bucket/v1/list": {
            "get": {
                "summary": "存储空间列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "当前页数",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "查询总页数",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Bearer 31a165baebe6dec616b1f8f3207b4273",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\",\"message\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/catalogue/v1/create": {
            "post": {
                "summary": "目录对象创建",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 31a165baebe6dec616b1f8f3207b4273",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "添加请求参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.CatalogueCreateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\",\"message\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/catalogue/v1/detail": {
            "get": {
                "summary": "目录对象详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "存储空间名称",
                        "name": "bucket_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "存储空间ID",
                        "name": "bucket_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "目录对象名称",
                        "name": "catalogue_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "目录对象ID",
                        "name": "catalogue_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Bearer 31a165baebe6dec616b1f8f3207b4273",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\",\"message\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/v1/login": {
            "post": {
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "添加请求参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.LoginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\",\"message\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/v1/register": {
            "post": {
                "summary": "用户注册接口",
                "parameters": [
                    {
                        "description": "添加请求参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.RegisterReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\",\"message\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/v1/userinfo": {
            "get": {
                "summary": "用户详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 31a165baebe6dec616b1f8f3207b4273",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\",\"message\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/v1/userupdata": {
            "put": {
                "summary": "用户更新",
                "parameters": [
                    {
                        "description": "添加请求参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.UpdataReq"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Bearer 31a165baebe6dec616b1f8f3207b4273",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\",\"message\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "request.BucketAddReq": {
            "type": "object",
            "required": [
                "access_key",
                "alias",
                "bucket_name",
                "secret_key",
                "zone"
            ],
            "properties": {
                "access_key": {
                    "type": "string"
                },
                "alias": {
                    "type": "string"
                },
                "bucket_name": {
                    "type": "string"
                },
                "secret_key": {
                    "type": "string"
                },
                "zone": {
                    "type": "string"
                }
            }
        },
        "request.CatalogueCreateReq": {
            "type": "object",
            "required": [
                "bucket_id",
                "bucket_name",
                "disk_name"
            ],
            "properties": {
                "bucket_id": {
                    "type": "integer"
                },
                "bucket_name": {
                    "type": "string"
                },
                "disk_name": {
                    "type": "string"
                }
            }
        },
        "request.DeleteBucketReq": {
            "type": "object",
            "required": [
                "bucketname",
                "id"
            ],
            "properties": {
                "bucketname": {
                    "type": "string"
                },
                "id": {
                    "description": "bucketId",
                    "type": "integer"
                }
            }
        },
        "request.LoginReq": {
            "type": "object",
            "required": [
                "mobile",
                "password"
            ],
            "properties": {
                "mobile": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "request.RegisterReq": {
            "type": "object",
            "required": [
                "mobile",
                "password",
                "username"
            ],
            "properties": {
                "mobile": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "request.UpdataReq": {
            "type": "object",
            "required": [
                "username"
            ],
            "properties": {
                "username": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
